# Generated by Django 3.2.4 on 2022-08-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keydev_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя получателя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('telegram_chat_id', models.CharField(max_length=10, verbose_name='ID чата в Telegram')),
            ],
            options={
                'verbose_name': 'Внутренний получатель',
                'verbose_name_plural': 'Внутренние получатели',
            },
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='team',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
            preserve_default=False,
        ),
    ]
