# Generated by Django 3.2.4 on 2022-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keydev_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(verbose_name='Напишите нам сообщение'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ф.И.О \\ Наименование организации'),
        ),
    ]
