# Generated by Django 3.2.4 on 2022-08-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keydev_app', '0002_auto_20220810_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='tags',
            new_name='icons',
        ),
    ]
