# Generated by Django 3.2.4 on 2022-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keydev_app', '0005_employee_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='background_color',
            field=models.CharField(choices=[('blue', 'blue'), ('red', 'red')], max_length=255),
        ),
    ]
