version: '3.8'

services:
  frontend:
    restart: always
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/front_order/
    ports:
      - 3000:3000
    depends_on:
      - web
  redis:
    image: redis
    restart: always
  web:
    restart: always
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  worker:
    restart: always
    build:
      context: ./app
    env_file:
      - ./.env.dev
    command: ["celery", "-A", "keydev", "worker", "-l", "info"]
    depends_on:
      - web
      - redis
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=keydev_user
      - POSTGRES_PASSWORD=keydev_password
      - POSTGRES_DB=keydev_db

volumes:
  postgres_data: